table_mean:
  Entry_price: 20869.439935
  First_release_year: 2004.514415
  Year: 2012.268621
  Wheelbase: 2638.917542
  Width: 1890.907789
  Length: 4349.187311
  Height: 1528.703109
  Engine_size: 1.882031
  Seat_num: 4.884995
  Door_num: 4.390699
  
table_std:
  Entry_price: 18314.145652
  First_release_year: 4.623948
  Year: 4.267292
  Wheelbase: 192.614040
  Width: 151.733309
  Length: 413.011074
  Height: 120.692785
  Engine_size: 0.768230
  Seat_num: 0.812515
  Door_num: 0.985177

sales_mean: 16388.617371
sales_std: 19953.648240

categorical_columns:
  - Genmodel
  - Maker
  - Color
  - Bodytype
  - Gearbox
  - Fuel_type

categorical_mapping:
  Maker:
    0: Abarth
    1: Alfa Romeo
    2: Aston Martin
    3: Audi
    4: BMW
    5: Bentley
    6: Cadillac
    7: Chevrolet
    8: Chrysler
    9: Citroen
    10: DS
    11: Dacia
    12: Daewoo
    13: Daihatsu
    14: Dodge
    15: Ferrari
    16: Fiat
    17: Ford
    18: Honda
    19: Hummer
    20: Hyundai
    21: Infiniti
    22: Isuzu
    23: Jaguar
    24: Jeep
    25: Kia
    26: Lamborghini
    27: Land Rover
    28: Lexus
    29: Lotus
    30: MG
    31: MINI
    32: Maserati
    33: Maybach
    34: Mazda
    35: McLaren
    36: Mercedes-Benz
    37: Mitsubishi
    38: Nissan
    39: Perodua
    40: Peugeot
    41: Porsche
    42: Proton
    43: Renault
    44: Rolls-Royce
    45: Rover
    46: SEAT
    47: SKODA
    48: Saab
    49: Smart
    50: Ssangyong
    51: Subaru
    52: Suzuki
    53: TVR
    54: Toyota
    55: Vauxhall
    56: Volkswagen
    57: Volvo

  Genmodel:
    0: "'Cee''d'"
    1: "'Pro_Cee''d'"
    2: "09-Mar"
    3: "09-May"
    4: "1 Series"
    5: "1007"
    6: "106"
    7: "107"
    8: "108"
    9: "124 Spider"
    10: "159"
    11: "2 Series"
    12: "2008"
    13: "206"
    14: "207"
    15: "208"
    16: "25"
    17: "3"
    18: "3 Series"
    19: "3008"
    20: "300C"
    21: "306"
    22: "307"
    23: "308"
    24: "323"
    25: "350 Z"
    26: "360"
    27: "370 Z"
    28: "4"
    29: "4007"
    30: "406"
    31: "407"
    32: "45"
    33: "458"
    34: "488"
    35: "4C"
    36: "5"
    37: "5 Series"
    38: "500"
    39: "5008"
    40: "500L"
    41: "500X"
    42: "508"
    43: "540C"
    44: "57"
    45: "595"
    46: "6 Series"
    47: "607"
    48: "612"
    49: "62"
    50: "7 Series"
    51: "718 Boxster"
    52: "718 Cayman"
    53: "75"
    54: "807"
    55: "911"
    56: "A Class"
    57: "A1"
    58: "A2"
    59: "A3"
    60: "A4"
    61: "A5"
    62: "A6 Allroad"
    63: "A6 Avant"
    64: "A6 Saloon"
    65: "A6 Unspecified"
    66: "A7"
    67: "A8"
    68: "ADAM"
    69: "ASX"
    70: "AYGO"
    71: "Accent"
    72: "Accord"
    73: "Agila"
    74: "Alhambra"
    75: "Almera"
    76: "Altea"
    77: "Alto"
    78: "Amica"
    79: "Ampera"
    80: "Antara"
    81: "Arnage"
    82: "Arona"
    83: "Arosa"
    84: "Arteon"
    85: "Astra"
    86: "Ateca"
    87: "Auris"
    88: "Avenger"
    89: "Avensis"
    90: "Aventador"
    91: "Aveo"
    92: "B Class"
    93: "B-Max"
    94: "BLS"
    95: "BRZ"
    96: "Baleno"
    97: "Beetle"
    98: "Bentayga"
    99: "Berlingo"
    100: "Bipper Tepee"
    101: "Bora"
    102: "Boxster"
    103: "Bravo"
    104: "Brera"
    105: "Brooklands"
    106: "C Class"
    107: "C-Crosser"
    108: "C-HR"
    109: "C-Max"
    110: "C1"
    111: "C2"
    112: "C3"
    113: "C30"
    114: "C4"
    115: "C5"
    116: "C6"
    117: "C70"
    118: "C8"
    119: "CC"
    120: "CL"
    121: "CLA Class"
    122: "CLC Class"
    123: "CLK"
    124: "CLS"
    125: "CR-V"
    126: "CR-Z"
    127: "CT"
    128: "CT 200h"
    129: "CTS"
    130: "CX-3"
    131: "CX-5"
    132: "CX-7"
    133: "Caliber"
    134: "California"
    135: "Captiva"
    136: "Captur"
    137: "Caravelle"
    138: "Carens"
    139: "Carisma"
    140: "Cascada"
    141: "Cayenne"
    142: "Cayman"
    143: "Celerio"
    144: "Cerato"
    145: "Cherokee"
    146: "Citigo"
    147: "City Rover"
    148: "Civic"
    149: "Clio"
    150: "Clubman"
    151: "Colt"
    152: "Commander"
    153: "Compass"
    154: "Continental"
    155: "Copen"
    156: "Cordoba"
    157: "Corolla"
    158: "Corsa"
    159: "Countryman"
    160: "Coupe"
    161: "Croma"
    162: "Crossfire"
    163: "Crossland X"
    164: "Cruze"
    165: "Cube"
    166: "DB11"
    167: "DB9"
    168: "DBS"
    169: "DS3"
    170: "DS3 Cabrio"
    171: "DS4"
    172: "DS5"
    173: "Dawn"
    174: "Delta"
    175: "Demio"
    176: "Discovery"
    177: "Dispatch"
    178: "Doblo"
    179: "Duster"
    180: "E Class"
    181: "E-PACE"
    182: "Eclipse Cross"
    183: "EcoSport"
    184: "Edge"
    185: "Elantra"
    186: "Elise"
    187: "Eos"
    188: "Espace"
    189: "Evora"
    190: "Exeo"
    191: "Exige"
    192: "F-PACE"
    193: "F-Type"
    194: "F430"
    195: "FF"
    196: "FR-V"
    197: "FX"
    198: "Fabia"
    199: "Fiesta"
    200: "Fiorino"
    201: "Flying Spur"
    202: "Focus"
    203: "Forester"
    204: "Fox"
    205: "Freelander"
    206: "Fusion"
    207: "G Class"
    208: "GEN-2"
    209: "GL Class"
    210: "GLA Class"
    211: "GLC Class"
    212: "GLE Class"
    213: "GLS Class"
    214: "GS"
    215: "GS 250"
    216: "GS 300"
    217: "GS 450h"
    218: "GT"
    219: "GT-R"
    220: "GT86"
    221: "Galaxy"
    222: "Gallardo"
    223: "Genesis"
    224: "Getz"
    225: "Ghibli"
    226: "Ghost"
    227: "Giulia"
    228: "Giulietta"
    229: "Golf"
    230: "GranCabrio"
    231: "Grand C-Max"
    232: "Grand Cherokee"
    233: "Grand Scenic"
    234: "Grand Vitara"
    235: "Grand Voyager"
    236: "Grandis"
    237: "Grandland X"
    238: "Gransport"
    239: "Granturismo"
    240: "H3"
    241: "HR-V"
    242: "Hatch"
    243: "Huracan"
    244: "IS 200"
    245: "IS 220d"
    246: "IS 250"
    247: "IS 300"
    248: "IS F"
    249: "Ibiza"
    250: "Idea"
    251: "Ignis"
    252: "Impian"
    253: "Impreza"
    254: "Insight"
    255: "Insignia"
    256: "Ioniq"
    257: "Jazz"
    258: "Jetta"
    259: "Jimny"
    260: "Journey"
    261: "Juke"
    262: "Justy"
    263: "Ka"
    264: "Kadjar"
    265: "Kalos"
    266: "Kangoo"
    267: "Karoq"
    268: "Kelisa"
    269: "Kizashi"
    270: "Kodiaq"
    271: "Koleos"
    272: "Kona"
    273: "Korando"
    274: "Kuga"
    275: "Kyron"
    276: "LC 500"
    277: "LS 430"
    278: "LS 460"
    279: "LS 600h"
    280: "Lacetti"
    281: "Laguna"
    282: "Lancer"
    283: "Land Cruiser"
    284: "Leaf"
    285: "Legacy"
    286: "Legend"
    287: "Leon"
    288: "Levante"
    289: "Levorg"
    290: "Liana"
    291: "Logan MCV"
    292: "M Class"
    293: "MG3"
    294: "MG6"
    295: "MR2"
    296: "Macan"
    297: "Magentis"
    298: "Materia"
    299: "Matiz"
    300: "Matrix"
    301: "Maverick"
    302: "Mazda2"
    303: "Mazda3"
    304: "Mazda5"
    305: "Mazda6"
    306: "Megane"
    307: "Meriva"
    308: "MiTo"
    309: "Micra"
    310: "Mii"
    311: "Mirage"
    312: "Modus"
    313: "Mokka"
    314: "Monaro"
    315: "Mondeo"
    316: "Mulsanne"
    317: "Multipla"
    318: "Murano"
    319: "Murcielago"
    320: "Mustang"
    321: "Myvi"
    322: "NV200"
    323: "NX 200t"
    324: "NX 300h"
    325: "Nemo Multispace"
    326: "Neon"
    327: "Niro"
    328: "Nitro"
    329: "Note"
    330: "Nubira"
    331: "Octavia"
    332: "Omega"
    333: "Optima"
    334: "Orlando"
    335: "Outback"
    336: "Outlander"
    337: "PT Cruiser"
    338: "Paceman"
    339: "Panamera"
    340: "Panda"
    341: "Passat"
    342: "Pathfinder"
    343: "Patriot"
    344: "Phaeton"
    345: "Phantom"
    346: "Picanto"
    347: "Picnic"
    348: "Pixo"
    349: "Polo"
    350: "Previa"
    351: "Primera"
    352: "Prius"
    353: "Pulsar"
    354: "Puma"
    355: "Punto"
    356: "Q2"
    357: "Q3"
    358: "Q30"
    359: "Q5"
    360: "Q50"
    361: "Q60"
    362: "Q7"
    363: "QX30"
    364: "Qashqai"
    365: "Quattroporte"
    366: "Qubo"
    367: "R Class"
    368: "R8"
    369: "RAV4"
    370: "RC 200t"
    371: "RC 300h"
    372: "RC F"
    373: "RCZ"
    374: "RX 300"
    375: "RX 350"
    376: "RX 400h"
    377: "RX-8"
    378: "Range Rover"
    379: "Rapid"
    380: "Rapide"
    381: "Renegade"
    382: "Rexton"
    383: "Rio"
    384: "Roadster"
    385: "Rodius"
    386: "Roomster"
    387: "S Class"
    388: "S-Max"
    389: "S-Type"
    390: "S2000"
    391: "S40"
    392: "S60"
    393: "S80"
    394: "S90"
    395: "SC 430"
    396: "SL Class"
    397: "SLC"
    398: "SLK"
    399: "STS"
    400: "SX4"
    401: "Sandero"
    402: "Santa Fe"
    403: "Satria Neo"
    404: "Savvy"
    405: "Saxo"
    406: "Scenic"
    407: "Scirocco"
    408: "Scudo"
    409: "Sebring"
    410: "Sedici"
    411: "Sedona"
    412: "Seicento"
    413: "Sharan"
    414: "Shogun"
    415: "Signum"
    416: "Silver Seraph"
    417: "Sirion"
    418: "Sonata"
    419: "Sorento"
    420: "Soul"
    421: "Space Star"
    422: "Space Wagon"
    423: "SpaceTourer"
    424: "Spark"
    425: "Spider"
    426: "Splash"
    427: "Sportage"
    428: "Spyder"
    429: "Stelvio"
    430: "Stilo"
    431: "Stonic"
    432: "Stream"
    433: "Streetka"
    434: "Streetwise"
    435: "Superb"
    436: "Swift"
    437: "T-Roc"
    438: "TF"
    439: "TT"
    440: "Tacuma"
    441: "Terios"
    442: "Terracan"
    443: "Terrano"
    444: "Tigra"
    445: "Tiguan"
    446: "Tipo"
    447: "Tivoli"
    448: "Toledo"
    449: "Touareg"
    450: "Touran"
    451: "Tourneo Connect"
    452: "Trajet"
    453: "Traveller"
    454: "Trax"
    455: "Tribute"
    456: "Trooper"
    457: "Tucson"
    458: "Tuscan"
    459: "Twingo"
    460: "Ulysse"
    461: "Urbancruiser"
    462: "V Class"
    463: "V40"
    464: "V50"
    465: "V60"
    466: "V70"
    467: "V90"
    468: "VX220"
    469: "VXR8"
    470: "Vaneo"
    471: "Vectra"
    472: "Vel Satis"
    473: "Veloster"
    474: "Venga"
    475: "Verso"
    476: "Viano"
    477: "Vitara"
    478: "Viva"
    479: "Vivaro"
    480: "Volt"
    481: "Voyager"
    482: "Wagon R"
    483: "Wind"
    484: "Wira"
    485: "Wraith"
    486: "Wrangler"
    487: "X-Trail"
    488: "X-Type"
    489: "X1"
    490: "X3"
    491: "X4"
    492: "X5"
    493: "X6"
    494: "XC60"
    495: "XC70"
    496: "XC90"
    497: "XE"
    498: "XF"
    499: "XJ"
    500: "XK"
    501: "XV"
    502: "Yaris"
    503: "Yeti"
    504: "Ypsilon"
    505: "Z4"
    506: "ZR"
    507: "ZS"
    508: "ZT"
    509: "Zafira"
    510: "forfour"
    511: "fortwo"
    512: "i10"
    513: "i20"
    514: "i3"
    515: "i30"
    516: "i40"
    517: "i8"
    518: "i800"
    519: "iQ"
    520: "ix20"
    521: "ix35"
    522: "up!"

  Color:
    0: Beige
    1: Black
    2: Blue
    3: Bronze
    4: Brown
    5: Burgundy
    6: Gold
    7: Green
    8: Grey
    9: Indigo
    10: Magenta
    11: Maroon
    12: Multicolour
    13: Navy
    14: Orange
    15: Pink
    16: Purple
    17: Red
    18: Silver
    19: Turquoise
    20: White
    21: Yellow

  Bodytype:
    0: "Car Derived Van"
    1: "Combi Van"
    2: "Convertible"
    3: "Coupe"
    4: "Estate"
    5: "Hatchback"
    6: "Limousine"
    7: "MPV"
    8: "Minibus"
    9: "Panel Van"
    10: "SUV"
    11: "Saloon"
    12: "Window Van"

  Gearbox:
    0: "Automatic"
    1: "Manual"
    2: "Semi-Automatic"
    
  Fuel_type:
    0: "Bi Fuel"
    1: "Diesel"
    2: "Diesel Hybrid"
    3: "Electric"
    4: "Hybrid  Diesel/Electric"
    5: "Hybrid  Diesel/Electric Plug-in"
    6: "Hybrid  Petrol/Electric"
    7: "Hybrid  Petrol/Electric Plug-in"
    8: "Petrol"
    9: "Petrol Ethanol"
    10: "Petrol Hybrid"
    11: "Petrol Plug-in Hybrid"